cpp_files=sim_main.cpp
files=../src/armleocpu_clint.v
includepaths=
defines=-DDEBUG_CLINT
verilator_options=-Wno-UNOPTFLAT -Wno-DECLFILENAME # -LDFLAGS "-ggdb" -CFLAGS "-ggdb"
top=armleocpu_clint
OPT=-ggdb
include VerilatorSimulate.mk